name: Deploy Tools

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for Turbo to compare properly

      - run: corepack enable && pnpm install

      - name: Build changed projects
        run: turbo run build --filter=projects/...

      - name: Prepare public folder
        run: |
          mkdir public
          for dir in projects/*; do
            if [ -d "$dir/dist" ]; then
              cp -r $dir/dist public/$(basename $dir)
            fi
          done

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          keep_files: true 